language: node_js
node_js: stable

cache:
    directories:
      - node_modules

before_install:
  - npm install -g hexo-cli
  - export TZ='Asia/Shanghai'

#before_script:
 # - npm install -g gulp

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo c
  - hexo g

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "coffeeZhou"
#   - git config user.email "632347712@qq.com"
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - master
# env:
#  global:
#    - GH_REF: https://github.com/coffeeZhou/coffeeZhou.github.io.git

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public